spring:
  application:
    name: itoken-zuul
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8769

#app:
#  version: 1.0.1

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

