spring:
  application:
    name: itoken-service-sso
  boot:
    admin:
      client:
        url: http://192.168.22.87:8084
  zipkin:
    base-url: http://192.168.22.87:9411
  datasource:
    druid:
      url: jdbc:mysql://192.168.1.5:3306/itoken-service-admin?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8503

feign:
  hystrix:
    enable: true

mybatis:
  type-aliases-package: com.funtl.itoken.common.domain
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    serviceUrl:
      default-zone: http://192.168.22.87:8761/eureka/,http://192.168.22.87:8861/eureka/,http://192.168.22.87:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info






