spring:
  application:
    name: itoken-zipkin

server:
  port: 9411

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

management:
  metries:
    web:
      server:
        auto-time-requests: false