spring:
  application:
    name: itoken-zuul

server:
  port: 8769

app:
  version: 1.0.1

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

#zuul:
#  routes:
#    api-a:
#      path: /api/a/**
#      serviceId: