spring:
  application:
    name: itoken-service-admin
  boot:
    admin:
      client:
        url: http://192.168.22.87:8084
  zipkin:
    base-url: http://192.168.22.87:9411
  datasource:
    druid:
      url: jdbc:mysql://192.168.22.58:3306/itoken-service-admin?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8502

eureka:
  client:
    service-url:
      default-zone: http://192.168.22.87:8761/eureka/,http://192.168.22.87:8861/eureka/,http://192.168.22.87:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info