spring:
  application:
    name: itoken-zipkin
  boot:
    admin:
      client:
        url: http://192.168.22.87:8084
  zipkin:
    base-url: http://192.168.22.87:9411

server:
  port: 9411

#eureka 集群
eureka:
  client:
    service-url:
      default-zone: http://192.168.22.87:8761/eureka/,http://192.168.22.87:8861/eureka/,http://192.168.22.87:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
  metrics:
    web:
      server:
        auto-time-requests: false