spring:
  application:
    name: itoken-eureka

server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.22.87
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://192.168.22.87:8761/eureka/,http://192.168.22.87:8861/eureka/,http://192.168.22.87:8961/eureka/
